version: '2'
services:
  scimgateway:
    build: 
      context: .
      dockerfile: Dockerfile
    image: scimgateway:latest
    container_name: scimgateway
    hostname:
      scimgateway
    volumes:
      - /home/scimgateway/config:/home/scimgateway/config:rw
    volumes_from:
      - scimgateway-data
    ports:
      - "8880:8880"
    environment:
      - ENVIRONMENT=development
      - PORT=8880
      - SEED=localhost
    restart: on-failure:3
            
  scimgateway-data:
    image: scimgateway-data:latest
    container_name: scimgateway-data
    build:
      context: .
      dockerfile: DataDockerfile
