// https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.json
module.exports.codes = [
  {
    "name": "AFGHANISTAN",
    "alpha-2": "AF",
    "country-code": "004"
  }, {
    "name": "ÅLAND ISLANDS",
    "alpha-2": "AX",
    "country-code": "248"
  }, {
    "name": "ALBANIA",
    "alpha-2": "AL",
    "country-code": "008"
  }, {
    "name": "ALGERIA",
    "alpha-2": "DZ",
    "country-code": "012"
  }, {
    "name": "AMERICAN SAMOA",
    "alpha-2": "AS",
    "country-code": "016"
  }, {
    "name": "ANDORRA",
    "alpha-2": "AD",
    "country-code": "020"
  }, {
    "name": "ANGOLA",
    "alpha-2": "AO",
    "country-code": "024"
  }, {
    "name": "ANGUILLA",
    "alpha-2": "AI",
    "country-code": "660"
  }, {
    "name": "ANTARCTICA",
    "alpha-2": "AQ",
    "country-code": "010"
  }, {
    "name": "ANTIGUA AND BARBUDA",
    "alpha-2": "AG",
    "country-code": "028"
  }, {
    "name": "ARGENTINA",
    "alpha-2": "AR",
    "country-code": "032"
  }, {
    "name": "ARMENIA",
    "alpha-2": "AM",
    "country-code": "051"
  }, {
    "name": "ARUBA",
    "alpha-2": "AW",
    "country-code": "533"
  }, {
    "name": "AUSTRALIA",
    "alpha-2": "AU",
    "country-code": "036"
  }, {
    "name": "AUSTRIA",
    "alpha-2": "AT",
    "country-code": "040"
  }, {
    "name": "AZERBAIJAN",
    "alpha-2": "AZ",
    "country-code": "031"
  }, {
    "name": "BAHAMAS",
    "alpha-2": "BS",
    "country-code": "044"
  }, {
    "name": "BAHRAIN",
    "alpha-2": "BH",
    "country-code": "048"
  }, {
    "name": "BANGLADESH",
    "alpha-2": "BD",
    "country-code": "050"
  }, {
    "name": "BARBADOS",
    "alpha-2": "BB",
    "country-code": "052"
  }, {
    "name": "BELARUS",
    "alpha-2": "BY",
    "country-code": "112"
  }, {
    "name": "BELGIUM",
    "alpha-2": "BE",
    "country-code": "056"
  }, {
    "name": "BELIZE",
    "alpha-2": "BZ",
    "country-code": "084"
  }, {
    "name": "BENIN",
    "alpha-2": "BJ",
    "country-code": "204"
  }, {
    "name": "BERMUDA",
    "alpha-2": "BM",
    "country-code": "060"
  }, {
    "name": "BHUTAN",
    "alpha-2": "BT",
    "country-code": "064"
  }, {
    "name": "BOLIVIA (PLURINATIONAL STATE OF)",
    "alpha-2": "BO",
    "country-code": "068"
  }, {
    "name": "BONAIRE, SINT EUSTATIUS AND SABA",
    "alpha-2": "BQ",
    "country-code": "535"
  }, {
    "name": "BOSNIA AND HERZEGOVINA",
    "alpha-2": "BA",
    "country-code": "070"
  }, {
    "name": "BOTSWANA",
    "alpha-2": "BW",
    "country-code": "072"
  }, {
    "name": "BOUVET ISLAND",
    "alpha-2": "BV",
    "country-code": "074"
  }, {
    "name": "BRAZIL",
    "alpha-2": "BR",
    "country-code": "076"
  }, {
    "name": "BRITISH INDIAN OCEAN TERRITORY",
    "alpha-2": "IO",
    "country-code": "086"
  }, {
    "name": "BRUNEI DARUSSALAM",
    "alpha-2": "BN",
    "country-code": "096"
  }, {
    "name": "BULGARIA",
    "alpha-2": "BG",
    "country-code": "100"
  }, {
    "name": "BURKINA FASO",
    "alpha-2": "BF",
    "country-code": "854"
  }, {
    "name": "BURUNDI",
    "alpha-2": "BI",
    "country-code": "108"
  }, {
    "name": "CABO VERDE",
    "alpha-2": "CV",
    "country-code": "132"
  }, {
    "name": "CAMBODIA",
    "alpha-2": "KH",
    "country-code": "116"
  }, {
    "name": "CAMEROON",
    "alpha-2": "CM",
    "country-code": "120"
  }, {
    "name": "CANADA",
    "alpha-2": "CA",
    "country-code": "124"
  }, {
    "name": "CAYMAN ISLANDS",
    "alpha-2": "KY",
    "country-code": "136"
  }, {
    "name": "CENTRAL AFRICAN REPUBLIC",
    "alpha-2": "CF",
    "country-code": "140"
  }, {
    "name": "CHAD",
    "alpha-2": "TD",
    "country-code": "148"
  }, {
    "name": "CHILE",
    "alpha-2": "CL",
    "country-code": "152"
  }, {
    "name": "CHINA",
    "alpha-2": "CN",
    "country-code": "156"
  }, {
    "name": "CHRISTMAS ISLAND",
    "alpha-2": "CX",
    "country-code": "162"
  }, {
    "name": "COCOS (KEELING) ISLANDS",
    "alpha-2": "CC",
    "country-code": "166"
  }, {
    "name": "COLOMBIA",
    "alpha-2": "CO",
    "country-code": "170"
  }, {
    "name": "COMOROS",
    "alpha-2": "KM",
    "country-code": "174"
  }, {
    "name": "CONGO",
    "alpha-2": "CG",
    "country-code": "178"
  }, {
    "name": "CONGO, DEMOCRATIC REPUBLIC OF THE",
    "alpha-2": "CD",
    "country-code": "180"
  }, {
    "name": "COOK ISLANDS",
    "alpha-2": "CK",
    "country-code": "184"
  }, {
    "name": "COSTA RICA",
    "alpha-2": "CR",
    "country-code": "188"
  }, {
    "name": "CôTE D'IVOIRE",
    "alpha-2": "CI",
    "country-code": "384"
  }, {
    "name": "CROATIA",
    "alpha-2": "HR",
    "country-code": "191"
  }, {
    "name": "CUBA",
    "alpha-2": "CU",
    "country-code": "192"
  }, {
    "name": "CURAçAO",
    "alpha-2": "CW",
    "country-code": "531"
  }, {
    "name": "CYPRUS",
    "alpha-2": "CY",
    "country-code": "196"
  }, {
    "name": "CZECHIA",
    "alpha-2": "CZ",
    "country-code": "203"
  }, {
    "name": "DENMARK",
    "alpha-2": "DK",
    "country-code": "208"
  }, {
    "name": "DJIBOUTI",
    "alpha-2": "DJ",
    "country-code": "262"
  }, {
    "name": "DOMINICA",
    "alpha-2": "DM",
    "country-code": "212"
  }, {
    "name": "DOMINICAN REPUBLIC",
    "alpha-2": "DO",
    "country-code": "214"
  }, {
    "name": "ECUADOR",
    "alpha-2": "EC",
    "country-code": "218"
  }, {
    "name": "EGYPT",
    "alpha-2": "EG",
    "country-code": "818"
  }, {
    "name": "EL SALVADOR",
    "alpha-2": "SV",
    "country-code": "222"
  }, {
    "name": "EQUATORIAL GUINEA",
    "alpha-2": "GQ",
    "country-code": "226"
  }, {
    "name": "ERITREA",
    "alpha-2": "ER",
    "country-code": "232"
  }, {
    "name": "ESTONIA",
    "alpha-2": "EE",
    "country-code": "233"
  }, {
    "name": "ESWATINI",
    "alpha-2": "SZ",
    "country-code": "748"
  }, {
    "name": "ETHIOPIA",
    "alpha-2": "ET",
    "country-code": "231"
  }, {
    "name": "FALKLAND ISLANDS (MALVINAS)",
    "alpha-2": "FK",
    "country-code": "238"
  }, {
    "name": "FAROE ISLANDS",
    "alpha-2": "FO",
    "country-code": "234"
  }, {
    "name": "FIJI",
    "alpha-2": "FJ",
    "country-code": "242"
  }, {
    "name": "FINLAND",
    "alpha-2": "FI",
    "country-code": "246"
  }, {
    "name": "FRANCE",
    "alpha-2": "FR",
    "country-code": "250"
  }, {
    "name": "FRENCH GUIANA",
    "alpha-2": "GF",
    "country-code": "254"
  }, {
    "name": "FRENCH POLYNESIA",
    "alpha-2": "PF",
    "country-code": "258"
  }, {
    "name": "FRENCH SOUTHERN TERRITORIES",
    "alpha-2": "TF",
    "country-code": "260"
  }, {
    "name": "GABON",
    "alpha-2": "GA",
    "country-code": "266"
  }, {
    "name": "GAMBIA",
    "alpha-2": "GM",
    "country-code": "270"
  }, {
    "name": "GEORGIA",
    "alpha-2": "GE",
    "country-code": "268"
  }, {
    "name": "GERMANY",
    "alpha-2": "DE",
    "country-code": "276"
  }, {
    "name": "GHANA",
    "alpha-2": "GH",
    "country-code": "288"
  }, {
    "name": "GIBRALTAR",
    "alpha-2": "GI",
    "country-code": "292"
  }, {
    "name": "GREECE",
    "alpha-2": "GR",
    "country-code": "300"
  }, {
    "name": "GREENLAND",
    "alpha-2": "GL",
    "country-code": "304"
  }, {
    "name": "GRENADA",
    "alpha-2": "GD",
    "country-code": "308"
  }, {
    "name": "GUADELOUPE",
    "alpha-2": "GP",
    "country-code": "312"
  }, {
    "name": "GUAM",
    "alpha-2": "GU",
    "country-code": "316"
  }, {
    "name": "GUATEMALA",
    "alpha-2": "GT",
    "country-code": "320"
  }, {
    "name": "GUERNSEY",
    "alpha-2": "GG",
    "country-code": "831"
  }, {
    "name": "GUINEA",
    "alpha-2": "GN",
    "country-code": "324"
  }, {
    "name": "GUINEA-BISSAU",
    "alpha-2": "GW",
    "country-code": "624"
  }, {
    "name": "GUYANA",
    "alpha-2": "GY",
    "country-code": "328"
  }, {
    "name": "HAITI",
    "alpha-2": "HT",
    "country-code": "332"
  }, {
    "name": "HEARD ISLAND AND MCDONALD ISLANDS",
    "alpha-2": "HM",
    "country-code": "334"
  }, {
    "name": "HOLY SEE",
    "alpha-2": "VA",
    "country-code": "336"
  }, {
    "name": "HONDURAS",
    "alpha-2": "HN",
    "country-code": "340"
  }, {
    "name": "HONG KONG",
    "alpha-2": "HK",
    "country-code": "344"
  }, {
    "name": "HUNGARY",
    "alpha-2": "HU",
    "country-code": "348"
  }, {
    "name": "ICELAND",
    "alpha-2": "IS",
    "country-code": "352"
  }, {
    "name": "INDIA",
    "alpha-2": "IN",
    "country-code": "356"
  }, {
    "name": "INDONESIA",
    "alpha-2": "ID",
    "country-code": "360"
  }, {
    "name": "IRAN (ISLAMIC REPUBLIC OF)",
    "alpha-2": "IR",
    "country-code": "364"
  }, {
    "name": "IRAQ",
    "alpha-2": "IQ",
    "country-code": "368"
  }, {
    "name": "IRELAND",
    "alpha-2": "IE",
    "country-code": "372"
  }, {
    "name": "ISLE OF MAN",
    "alpha-2": "IM",
    "country-code": "833"
  }, {
    "name": "ISRAEL",
    "alpha-2": "IL",
    "country-code": "376"
  }, {
    "name": "ITALY",
    "alpha-2": "IT",
    "country-code": "380"
  }, {
    "name": "JAMAICA",
    "alpha-2": "JM",
    "country-code": "388"
  }, {
    "name": "JAPAN",
    "alpha-2": "JP",
    "country-code": "392"
  }, {
    "name": "JERSEY",
    "alpha-2": "JE",
    "country-code": "832"
  }, {
    "name": "JORDAN",
    "alpha-2": "JO",
    "country-code": "400"
  }, {
    "name": "KAZAKHSTAN",
    "alpha-2": "KZ",
    "country-code": "398"
  }, {
    "name": "KENYA",
    "alpha-2": "KE",
    "country-code": "404"
  }, {
    "name": "KIRIBATI",
    "alpha-2": "KI",
    "country-code": "296"
  }, {
    "name": "KOREA (DEMOCRATIC PEOPLE'S REPUBLIC OF)",
    "alpha-2": "KP",
    "country-code": "408"
  }, {
    "name": "KOREA, REPUBLIC OF",
    "alpha-2": "KR",
    "country-code": "410"
  }, {
    "name": "KUWAIT",
    "alpha-2": "KW",
    "country-code": "414"
  }, {
    "name": "KYRGYZSTAN",
    "alpha-2": "KG",
    "country-code": "417"
  }, {
    "name": "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    "alpha-2": "LA",
    "country-code": "418"
  }, {
    "name": "LATVIA",
    "alpha-2": "LV",
    "country-code": "428"
  }, {
    "name": "LEBANON",
    "alpha-2": "LB",
    "country-code": "422"
  }, {
    "name": "LESOTHO",
    "alpha-2": "LS",
    "country-code": "426"
  }, {
    "name": "LIBERIA",
    "alpha-2": "LR",
    "country-code": "430"
  }, {
    "name": "LIBYA",
    "alpha-2": "LY",
    "country-code": "434"
  }, {
    "name": "LIECHTENSTEIN",
    "alpha-2": "LI",
    "country-code": "438"
  }, {
    "name": "LITHUANIA",
    "alpha-2": "LT",
    "country-code": "440"
  }, {
    "name": "LUXEMBOURG",
    "alpha-2": "LU",
    "country-code": "442"
  }, {
    "name": "MACAO",
    "alpha-2": "MO",
    "country-code": "446"
  }, {
    "name": "MADAGASCAR",
    "alpha-2": "MG",
    "country-code": "450"
  }, {
    "name": "MALAWI",
    "alpha-2": "MW",
    "country-code": "454"
  }, {
    "name": "MALAYSIA",
    "alpha-2": "MY",
    "country-code": "458"
  }, {
    "name": "MALDIVES",
    "alpha-2": "MV",
    "country-code": "462"
  }, {
    "name": "MALI",
    "alpha-2": "ML",
    "country-code": "466"
  }, {
    "name": "MALTA",
    "alpha-2": "MT",
    "country-code": "470"
  }, {
    "name": "MARSHALL ISLANDS",
    "alpha-2": "MH",
    "country-code": "584"
  }, {
    "name": "MARTINIQUE",
    "alpha-2": "MQ",
    "country-code": "474"
  }, {
    "name": "MAURITANIA",
    "alpha-2": "MR",
    "country-code": "478"
  }, {
    "name": "MAURITIUS",
    "alpha-2": "MU",
    "country-code": "480"
  }, {
    "name": "MAYOTTE",
    "alpha-2": "YT",
    "country-code": "175"
  }, {
    "name": "MEXICO",
    "alpha-2": "MX",
    "country-code": "484"
  }, {
    "name": "MICRONESIA (FEDERATED STATES OF)",
    "alpha-2": "FM",
    "country-code": "583"
  }, {
    "name": "MOLDOVA, REPUBLIC OF",
    "alpha-2": "MD",
    "country-code": "498"
  }, {
    "name": "MONACO",
    "alpha-2": "MC",
    "country-code": "492"
  }, {
    "name": "MONGOLIA",
    "alpha-2": "MN",
    "country-code": "496"
  }, {
    "name": "MONTENEGRO",
    "alpha-2": "ME",
    "country-code": "499"
  }, {
    "name": "MONTSERRAT",
    "alpha-2": "MS",
    "country-code": "500"
  }, {
    "name": "MOROCCO",
    "alpha-2": "MA",
    "country-code": "504"
  }, {
    "name": "MOZAMBIQUE",
    "alpha-2": "MZ",
    "country-code": "508"
  }, {
    "name": "MYANMAR",
    "alpha-2": "MM",
    "country-code": "104"
  }, {
    "name": "NAMIBIA",
    "alpha-2": "NA",
    "country-code": "516"
  }, {
    "name": "NAURU",
    "alpha-2": "NR",
    "country-code": "520"
  }, {
    "name": "NEPAL",
    "alpha-2": "NP",
    "country-code": "524"
  }, {
    "name": "NETHERLANDS",
    "alpha-2": "NL",
    "country-code": "528"
  }, {
    "name": "NEW CALEDONIA",
    "alpha-2": "NC",
    "country-code": "540"
  }, {
    "name": "NEW ZEALAND",
    "alpha-2": "NZ",
    "country-code": "554"
  }, {
    "name": "NICARAGUA",
    "alpha-2": "NI",
    "country-code": "558"
  }, {
    "name": "NIGER",
    "alpha-2": "NE",
    "country-code": "562"
  }, {
    "name": "NIGERIA",
    "alpha-2": "NG",
    "country-code": "566"
  }, {
    "name": "NIUE",
    "alpha-2": "NU",
    "country-code": "570"
  }, {
    "name": "NORFOLK ISLAND",
    "alpha-2": "NF",
    "country-code": "574"
  }, {
    "name": "NORTH MACEDONIA",
    "alpha-2": "MK",
    "country-code": "807"
  }, {
    "name": "NORTHERN MARIANA ISLANDS",
    "alpha-2": "MP",
    "country-code": "580"
  }, {
    "name": "NORWAY",
    "alpha-2": "NO",
    "country-code": "578"
  }, {
    "name": "OMAN",
    "alpha-2": "OM",
    "country-code": "512"
  }, {
    "name": "PAKISTAN",
    "alpha-2": "PK",
    "country-code": "586"
  }, {
    "name": "PALAU",
    "alpha-2": "PW",
    "country-code": "585"
  }, {
    "name": "PALESTINE, STATE OF",
    "alpha-2": "PS",
    "country-code": "275"
  }, {
    "name": "PANAMA",
    "alpha-2": "PA",
    "country-code": "591"
  }, {
    "name": "PAPUA NEW GUINEA",
    "alpha-2": "PG",
    "country-code": "598"
  }, {
    "name": "PARAGUAY",
    "alpha-2": "PY",
    "country-code": "600"
  }, {
    "name": "PERU",
    "alpha-2": "PE",
    "country-code": "604"
  }, {
    "name": "PHILIPPINES",
    "alpha-2": "PH",
    "country-code": "608"
  }, {
    "name": "PITCAIRN",
    "alpha-2": "PN",
    "country-code": "612"
  }, {
    "name": "POLAND",
    "alpha-2": "PL",
    "country-code": "616"
  }, {
    "name": "PORTUGAL",
    "alpha-2": "PT",
    "country-code": "620"
  }, {
    "name": "PUERTO RICO",
    "alpha-2": "PR",
    "country-code": "630"
  }, {
    "name": "QATAR",
    "alpha-2": "QA",
    "country-code": "634"
  }, {
    "name": "RéUNION",
    "alpha-2": "RE",
    "country-code": "638"
  }, {
    "name": "ROMANIA",
    "alpha-2": "RO",
    "country-code": "642"
  }, {
    "name": "RUSSIAN FEDERATION",
    "alpha-2": "RU",
    "country-code": "643"
  }, {
    "name": "RWANDA",
    "alpha-2": "RW",
    "country-code": "646"
  }, {
    "name": "SAINT BARTHéLEMY",
    "alpha-2": "BL",
    "country-code": "652"
  }, {
    "name": "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
    "alpha-2": "SH",
    "country-code": "654"
  }, {
    "name": "SAINT KITTS AND NEVIS",
    "alpha-2": "KN",
    "country-code": "659"
  }, {
    "name": "SAINT LUCIA",
    "alpha-2": "LC",
    "country-code": "662"
  }, {
    "name": "SAINT MARTIN (FRENCH PART)",
    "alpha-2": "MF",
    "country-code": "663"
  }, {
    "name": "SAINT PIERRE AND MIQUELON",
    "alpha-2": "PM",
    "country-code": "666"
  }, {
    "name": "SAINT VINCENT AND THE GRENADINES",
    "alpha-2": "VC",
    "country-code": "670"
  }, {
    "name": "SAMOA",
    "alpha-2": "WS",
    "country-code": "882"
  }, {
    "name": "SAN MARINO",
    "alpha-2": "SM",
    "country-code": "674"
  }, {
    "name": "SAO TOME AND PRINCIPE",
    "alpha-2": "ST",
    "country-code": "678"
  }, {
    "name": "SAUDI ARABIA",
    "alpha-2": "SA",
    "country-code": "682"
  }, {
    "name": "SENEGAL",
    "alpha-2": "SN",
    "country-code": "686"
  }, {
    "name": "SERBIA",
    "alpha-2": "RS",
    "country-code": "688"
  }, {
    "name": "SEYCHELLES",
    "alpha-2": "SC",
    "country-code": "690"
  }, {
    "name": "SIERRA LEONE",
    "alpha-2": "SL",
    "country-code": "694"
  }, {
    "name": "SINGAPORE",
    "alpha-2": "SG",
    "country-code": "702"
  }, {
    "name": "SINT MAARTEN (DUTCH PART)",
    "alpha-2": "SX",
    "country-code": "534"
  }, {
    "name": "SLOVAKIA",
    "alpha-2": "SK",
    "country-code": "703"
  }, {
    "name": "SLOVENIA",
    "alpha-2": "SI",
    "country-code": "705"
  }, {
    "name": "SOLOMON ISLANDS",
    "alpha-2": "SB",
    "country-code": "090"
  }, {
    "name": "SOMALIA",
    "alpha-2": "SO",
    "country-code": "706"
  }, {
    "name": "SOUTH AFRICA",
    "alpha-2": "ZA",
    "country-code": "710"
  }, {
    "name": "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    "alpha-2": "GS",
    "country-code": "239"
  }, {
    "name": "SOUTH SUDAN",
    "alpha-2": "SS",
    "country-code": "728"
  }, {
    "name": "SPAIN",
    "alpha-2": "ES",
    "country-code": "724"
  }, {
    "name": "SRI LANKA",
    "alpha-2": "LK",
    "country-code": "144"
  }, {
    "name": "SUDAN",
    "alpha-2": "SD",
    "country-code": "729"
  }, {
    "name": "SURINAME",
    "alpha-2": "SR",
    "country-code": "740"
  }, {
    "name": "SVALBARD AND JAN MAYEN",
    "alpha-2": "SJ",
    "country-code": "744"
  }, {
    "name": "SWEDEN",
    "alpha-2": "SE",
    "country-code": "752"
  }, {
    "name": "SWITZERLAND",
    "alpha-2": "CH",
    "country-code": "756"
  }, {
    "name": "SYRIAN ARAB REPUBLIC",
    "alpha-2": "SY",
    "country-code": "760"
  }, {
    "name": "TAIWAN, PROVINCE OF CHINA",
    "alpha-2": "TW",
    "country-code": "158"
  }, {
    "name": "TAJIKISTAN",
    "alpha-2": "TJ",
    "country-code": "762"
  }, {
    "name": "TANZANIA, UNITED REPUBLIC OF",
    "alpha-2": "TZ",
    "country-code": "834"
  }, {
    "name": "THAILAND",
    "alpha-2": "TH",
    "country-code": "764"
  }, {
    "name": "TIMOR-LESTE",
    "alpha-2": "TL",
    "country-code": "626"
  }, {
    "name": "TOGO",
    "alpha-2": "TG",
    "country-code": "768"
  }, {
    "name": "TOKELAU",
    "alpha-2": "TK",
    "country-code": "772"
  }, {
    "name": "TONGA",
    "alpha-2": "TO",
    "country-code": "776"
  }, {
    "name": "TRINIDAD AND TOBAGO",
    "alpha-2": "TT",
    "country-code": "780"
  }, {
    "name": "TUNISIA",
    "alpha-2": "TN",
    "country-code": "788"
  }, {
    "name": "TURKEY",
    "alpha-2": "TR",
    "country-code": "792"
  }, {
    "name": "TURKMENISTAN",
    "alpha-2": "TM",
    "country-code": "795"
  }, {
    "name": "TURKS AND CAICOS ISLANDS",
    "alpha-2": "TC",
    "country-code": "796"
  }, {
    "name": "TUVALU",
    "alpha-2": "TV",
    "country-code": "798"
  }, {
    "name": "UGANDA",
    "alpha-2": "UG",
    "country-code": "800"
  }, {
    "name": "UKRAINE",
    "alpha-2": "UA",
    "country-code": "804"
  }, {
    "name": "UNITED ARAB EMIRATES",
    "alpha-2": "AE",
    "country-code": "784"
  }, {
    "name": "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND",
    "alpha-2": "GB",
    "country-code": "826"
  }, {
    "name": "UNITED STATES OF AMERICA",
    "alpha-2": "US",
    "country-code": "840"
  }, {
    "name": "UNITED STATES MINOR OUTLYING ISLANDS",
    "alpha-2": "UM",
    "country-code": "581"
  }, {
    "name": "URUGUAY",
    "alpha-2": "UY",
    "country-code": "858"
  }, {
    "name": "UZBEKISTAN",
    "alpha-2": "UZ",
    "country-code": "860"
  }, {
    "name": "VANUATU",
    "alpha-2": "VU",
    "country-code": "548"
  }, {
    "name": "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
    "alpha-2": "VE",
    "country-code": "862"
  }, {
    "name": "VIET NAM",
    "alpha-2": "VN",
    "country-code": "704"
  }, {
    "name": "VIRGIN ISLANDS (BRITISH)",
    "alpha-2": "VG",
    "country-code": "092"
  }, {
    "name": "VIRGIN ISLANDS (U.S.)",
    "alpha-2": "VI",
    "country-code": "850"
  }, {
    "name": "WALLIS AND FUTUNA",
    "alpha-2": "WF",
    "country-code": "876"
  }, {
    "name": "WESTERN SAHARA",
    "alpha-2": "EH",
    "country-code": "732"
  }, {
    "name": "YEMEN",
    "alpha-2": "YE",
    "country-code": "887"
  }, {
    "name": "ZAMBIA",
    "alpha-2": "ZM",
    "country-code": "894"
  }, {
    "name": "ZIMBABWE",
    "alpha-2": "ZW",
    "country-code": "716"
  }
]
