name: Test Release Workflow

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
      TERM: "xterm-256color"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install Bun
      #   run: |
      #     curl -fsSL https://bun.sh/install | bash
      #     echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run release tests
        run: bun run test
